// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220727080938_mg_1")]
    partial class mg_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Abstract.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutBirthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Abstract.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactEmail")
                        .HasColumnType("int");

                    b.Property<int>("ContactMessage")
                        .HasColumnType("int");

                    b.Property<int>("ContactSubject")
                        .HasColumnType("int");

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EntityLayer.Abstract.EducationAndExpericence", b =>
                {
                    b.Property<int>("EducationAndExpericenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EducationAndExpericenceDate")
                        .HasColumnType("int");

                    b.Property<int>("EducationAndExpericenceDescription")
                        .HasColumnType("int");

                    b.Property<int>("EducationAndExpericenceLittleTitle")
                        .HasColumnType("int");

                    b.Property<int>("EducationAndExpericenceTitle")
                        .HasColumnType("int");

                    b.HasKey("EducationAndExpericenceID");

                    b.ToTable("EducationAndExpericences");
                });

            modelBuilder.Entity("EntityLayer.Abstract.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LinkFacebook")
                        .HasColumnType("int");

                    b.Property<int>("LinkInstagram")
                        .HasColumnType("int");

                    b.Property<int>("LinkLinkedin")
                        .HasColumnType("int");

                    b.Property<int>("LinkTwitter")
                        .HasColumnType("int");

                    b.HasKey("LinkID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("EntityLayer.Abstract.Service", b =>
                {
                    b.Property<int>("ServicesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ServicesDescription")
                        .HasColumnType("int");

                    b.Property<int>("ServicesTitle")
                        .HasColumnType("int");

                    b.HasKey("ServicesID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EntityLayer.Abstract.Skil", b =>
                {
                    b.Property<int>("SkilsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SkilsRatio")
                        .HasColumnType("int");

                    b.Property<int>("SkilsTitle")
                        .HasColumnType("int");

                    b.HasKey("SkilsID");

                    b.ToTable("Skils");
                });
#pragma warning restore 612, 618
        }
    }
}
